include: package:flutter_lints/flutter.yaml

## Keep root lints minimal; subprojects define their own
linter:
  rules:
    prefer_const_constructors: true
    REDACTED_TOKEN: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_relative_imports: true
    unnecessary_new: true
    unnecessary_const: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    # Exclude non-Flutter subprojects and backups from root analysis to reduce noise in Problems panel
    - admin/**
    - business/**
    - dashboard/**
    - enterprise-app/**
    - enterprise-onboarding-portal/**
    - enterprise-sdks-and-cli/**
    - functions/**
    - marketing/**
    - packages/**
    - scripts/**
    - tools/**
    - web/**
    - cleanup_backup_*/**
    - todo_fixme_backup_*/**
    - translation_backup/**
    - build/**
    # Exclude top-level Dart sources that aren't part of the `appoint/` app
    - lib/**
    - test/**
    - integration_test/**
    # As a safety net, exclude everything at the repo root; sub-projects like `appoint/`
    # have their own analysis_options.yaml and will still be analyzed separately.
    - '**/*'
  
  errors:
    # Treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    missing_return: warning
    
    # Allow having TODOs in the code
    todo: ignore
    
    # Allow having print statements in the code
    avoid_print: ignore