include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "lib/l10n/*.dart"
    - "test/**/*.mocks.dart"

linter:
  rules:
    - avoid_print
    # avoid_debug_print is not a recognized lint rule
    - prefer_const_constructors
    - REDACTED_TOKEN
    - prefer_const_declarations
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_parameters
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_single_quotes
    - always_use_package_imports
