name: App-Oint
services:
  - name: marketing
    source_dir: marketing
    github:
      repo: saharmor/app-oint
      branch: main
    run_command: npm start
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: NEXT_PUBLIC_API_URL
        value: "https://app-oint.com/api"
      - key: FIREBASE_PROJECT_ID
        value: app-oint-core
      - key: FIREBASE_APP_ID
        value: "1:944776470711:web:6f3c833ef110bca6c66d32"
    health_check:
      http_path: /
      initial_delay_seconds: 120
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 5
  - name: business
    source_dir: business
    github:
      repo: saharmor/app-oint
      branch: main
    run_command: flutter run --web-port=8080 --web-hostname=0.0.0.0 --release
    build_command: flutter build web --release --base-href="/business/"
    environment_slug: docker
    dockerfile_path: business/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /business
      - path: /business/*
    envs:
      - key: FLUTTER_WEB_PORT
        value: "8080"
      - key: FIREBASE_PROJECT_ID
        value: app-oint-core
      - key: FIREBASE_APP_ID
        value: "1:944776470711:web:6f3c833ef110bca6c66d32"
      - key: STRIPE_PUBLISHABLE_KEY
        value: REDACTED_STRIPE_PUBLISHABLE
    health_check:
      http_path: /business/
      initial_delay_seconds: 180
      period_seconds: 30
      timeout_seconds: 15
      success_threshold: 1
      failure_threshold: 5
  - name: admin
    source_dir: admin
    github:
      repo: saharmor/app-oint
      branch: main
    run_command: flutter run --web-port=8080 --web-hostname=0.0.0.0 --release
    build_command: flutter build web --release --base-href="/admin/"
    environment_slug: docker
    dockerfile_path: admin/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /admin
      - path: /admin/*
    envs:
      - key: FLUTTER_WEB_PORT
        value: "8080"
      - key: FIREBASE_PROJECT_ID
        value: app-oint-core
      - key: FIREBASE_APP_ID
        value: "1:944776470711:web:6f3c833ef110bca6c66d32"
    health_check:
      http_path: /admin/
      initial_delay_seconds: 180
      period_seconds: 30
      timeout_seconds: 15
      success_threshold: 1
      failure_threshold: 5
  - name: api
    source_dir: functions
    github:
      repo: saharmor/app-oint
      branch: main
    run_command: npm start
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
      - path: /api/*
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: FIREBASE_PROJECT_ID
        value: app-oint-core
      - key: FIREBASE_APP_ID
        value: "1:944776470711:web:6f3c833ef110bca6c66d32"
      - key: STRIPE_SECRET_KEY
        value: REDACTED_STRIPE_PUBLISHABLE
    health_check:
      http_path: /api/status
      initial_delay_seconds: 90
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3