# Prometheus Configuration for App-Oint Monitoring
global:
  scrape_interval: 15s     # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/alerting-rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Functions/API Service (Node.js) - Port 5001
  - job_name: 'functions'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['functions:5001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: 'functions'

  # Functions Health Endpoints
  - job_name: 'functions-health'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/health'
    static_configs:
      - targets: ['functions:5001']
    relabel_configs:
      - target_label: service
        replacement: 'functions'

  # Functions Liveness and Readiness
  - job_name: 'functions-probes'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['functions:5001']
        labels:
          probe_type: 'liveness'
    metrics_path: '/liveness'
    relabel_configs:
      - target_label: service
        replacement: 'functions'

  # Dashboard Service (Next.js) - Port 3000
  - job_name: 'dashboard'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/api/health'
    static_configs:
      - targets: ['dashboard:3000']
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: dashboard:3000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'dashboard'

  # Business Service (Static/Nginx) - Port 8081
  - job_name: 'business'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/health.html'
    static_configs:
      - targets: ['business:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: business:8081
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'business'

  # Admin Service (Static/Nginx) - Port 8082
  - job_name: 'admin'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/health.html'
    static_configs:
      - targets: ['admin:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: admin:8082
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'admin'

  # PostgreSQL Database - Port 5432
  - job_name: 'postgres'
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets: ['postgres:5432']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres:5432
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'postgres'

  # Redis Cache - Port 6379
  - job_name: 'redis'
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets: ['redis:6379']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis:6379
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'redis'

  # Grafana - Port 3001 (for self-monitoring)
  - job_name: 'grafana'
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: grafana:3001