apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qa-system
  template:
    metadata:
      labels:
        app: qa-system
    spec:
      containers:
      - name: qa-api
        image: app-qa-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: qa-secrets
              key: database-url
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
