# App-Oint Enterprise SLA Configuration
# Version: 1.0.0

# Service Level Agreements
slas:
  uptime:
    target: 99.9
    measurement_period: "monthly"
    calculation_method: "percentage"
    exclusions:
      - "scheduled_maintenance"
      - "force_majeure"
      - "customer_side_issues"
    
  latency:
    p50_target: 100  # milliseconds
    p95_target: 250  # milliseconds
    p99_target: 500  # milliseconds
    measurement_period: "5_minutes"
    
  availability:
    target: 99.95
    measurement_period: "monthly"
    
  error_rate:
    target: 0.1  # percentage
    measurement_period: "5_minutes"
    threshold_breach: 1.0  # percentage

# Monitoring Rules
monitoring:
  # API Endpoint Monitoring
  endpoints:
    - name: "api_health"
      url: "https://api.appoint.com/health"
      method: "GET"
      expected_status: 200
      timeout: 5
      check_interval: 30
      
    - name: "auth_endpoint"
      url: "https://api.appoint.com/auth/login"
      method: "POST"
      expected_status: 200
      timeout: 10
      check_interval: 60
      
    - name: "businesses_endpoint"
      url: "https://api.appoint.com/api/businesses/search"
      method: "GET"
      expected_status: 200
      timeout: 15
      check_interval: 120
      
    - name: "bookings_endpoint"
      url: "https://api.appoint.com/api/bookings"
      method: "GET"
      expected_status: 200
      timeout: 15
      check_interval: 120

  # Database Monitoring
  database:
    - name: "postgres_connection"
      type: "postgres"
      host: "db.appoint.com"
      port: 5432
      database: "appoint_prod"
      check_interval: 60
      
    - name: "redis_connection"
      type: "redis"
      host: "redis.appoint.com"
      port: 6379
      check_interval: 30

  # External Service Monitoring
  external_services:
    - name: "firebase_health"
      url: "https://firebase.google.com"
      method: "GET"
      timeout: 10
      check_interval: 300
      
    - name: "email_service"
      url: "https://api.sendgrid.com/v3/mail/settings"
      method: "GET"
      timeout: 15
      check_interval: 600

# Alerting Configuration
alerts:
  # Uptime Alerts
  uptime:
    warning_threshold: 99.5
    critical_threshold: 99.0
    notification_channels:
      - "email"
      - "slack"
      - "pagerduty"
    
  # Latency Alerts
  latency:
    p99_warning: 400  # milliseconds
    p99_critical: 600  # milliseconds
    p95_warning: 200  # milliseconds
    p95_critical: 300  # milliseconds
    notification_channels:
      - "email"
      - "slack"
      - "pagerduty"
      
  # Error Rate Alerts
  error_rate:
    warning_threshold: 0.5  # percentage
    critical_threshold: 1.0  # percentage
    notification_channels:
      - "email"
      - "slack"
      - "pagerduty"
      - "phone"

# Per-API-Key Telemetry
telemetry:
  api_keys:
    enabled: true
    metrics:
      - "request_count"
      - "response_time"
      - "error_count"
      - "data_transfer"
      - "endpoint_usage"
    retention_period: "90_days"
    aggregation_interval: "1_hour"
    
  # Custom Metrics
  custom_metrics:
    - name: "active_users"
      type: "gauge"
      description: "Number of active users per API key"
      
    - name: "booking_creation_rate"
      type: "counter"
      description: "Rate of booking creation per API key"
      
    - name: "data_export_size"
      type: "histogram"
      description: "Size of data exports per API key"

# Anomaly Detection
anomaly_detection:
  enabled: true
  algorithms:
    - "statistical_threshold"
    - "moving_average"
    - "machine_learning"
    
  # Statistical Threshold Rules
  statistical_threshold:
    sensitivity: "medium"  # low, medium, high
    window_size: "1_hour"
    std_dev_multiplier: 2.0
    
  # Moving Average Rules
  moving_average:
    window_size: "24_hours"
    alert_threshold: 3.0  # standard deviations
    
  # Machine Learning Rules
  machine_learning:
    model_type: "isolation_forest"
    training_period: "30_days"
    retrain_interval: "7_days"
    confidence_threshold: 0.95

# Webhook Configuration
webhooks:
  # Error Spike Webhooks
  error_spikes:
    enabled: true
    url: "https://webhooks.appoint.com/error-spikes"
    events:
      - "error_rate_breach"
      - "latency_breach"
      - "uptime_breach"
    retry_policy:
      max_retries: 3
      retry_delay: "5_minutes"
      
  # Latency Breach Webhooks
  latency_breaches:
    enabled: true
    url: "https://webhooks.appoint.com/latency-breaches"
    events:
      - "p99_latency_breach"
      - "p95_latency_breach"
    retry_policy:
      max_retries: 3
      retry_delay: "2_minutes"
      
  # Custom Webhooks
  custom:
    - name: "enterprise_customer_alert"
      url: "https://enterprise.appoint.com/webhooks/customer-alerts"
      events:
        - "sla_breach"
        - "service_degradation"
      authentication:
        type: "bearer_token"
        token: "${ENTERPRISE_WEBHOOK_TOKEN}"

# Dashboard Configuration
dashboards:
  # Per-API-Key Dashboard
  api_key_dashboard:
    enabled: true
    metrics:
      - "request_rate"
      - "response_time_p99"
      - "error_rate"
      - "data_transfer"
      - "active_endpoints"
    time_range: "24_hours"
    refresh_interval: "30_seconds"
    
  # Enterprise Dashboard
  enterprise_dashboard:
    enabled: true
    metrics:
      - "overall_uptime"
      - "average_latency"
      - "total_requests"
      - "error_rate"
      - "active_customers"
    time_range: "7_days"
    refresh_interval: "5_minutes"

# Compliance and Reporting
compliance:
  # SOC-2 Compliance
  soc2:
    enabled: true
    controls:
      - "availability_monitoring"
      - "performance_monitoring"
      - "error_tracking"
      - "audit_logging"
    reporting_interval: "monthly"
    
  # SLA Reporting
  sla_reports:
    enabled: true
    frequency: "monthly"
    recipients:
      - "enterprise@appoint.com"
      - "customers@appoint.com"
    format: "pdf"
    include_metrics:
      - "uptime_percentage"
      - "average_latency"
      - "error_rate"
      - "sla_breaches"

# Maintenance Windows
maintenance:
  scheduled_maintenance:
    enabled: true
    notification_period: "7_days"
    max_duration: "4_hours"
    allowed_windows:
      - day: "sunday"
        start_time: "02:00"
        end_time: "06:00"
        timezone: "UTC"
      - day: "saturday"
        start_time: "04:00"
        end_time: "08:00"
        timezone: "UTC" 