groups:
  - name: app-oint-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_request_total{status=~"5.."}[5m]) / rate(http_request_total[5m]) > 0.01
        for: 5m; labels:{severity: critical}
        annotations:{summary:"High error rate",description:"{{ $value | humanizePercentage }} errors"}
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_ms_bucket[5m])) > 500
        for: 5m; labels:{severity: warning}
      - alert: HighCPUUsage
        expr: rate(process_cpu_user_seconds_total[5m])*100 > 80
        for: 5m; labels:{severity: warning}
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes/1024/1024 > 1024
        for: 5m; labels:{severity: warning} 