apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-oint-functions-hpa
  namespace: app-oint
  labels:
    app: app-oint
    component: functions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-oint-functions
  minReplicas: 2
  maxReplicas: 20
  metrics:
    # CPU-based scaling - scale when average CPU usage exceeds 80%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    # Memory-based scaling - scale when average memory usage exceeds 75%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Wait 1 minute before scaling up again
      policies:
      - type: Percent
        value: 50     # Scale up by 50% of current replicas
        periodSeconds: 60
      - type: Pods
        value: 2      # Or add 2 pods, whichever is smaller
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 10     # Scale down by 10% of current replicas
        periodSeconds: 60
      selectPolicy: Min

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-oint-dashboard-hpa
  namespace: app-oint
  labels:
    app: app-oint
    component: dashboard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-oint-dashboard
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 15
        periodSeconds: 60
      selectPolicy: Min

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-oint-marketing-hpa
  namespace: app-oint
  labels:
    app: app-oint
    component: marketing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-oint-marketing
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
      selectPolicy: Min

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-oint-admin-hpa
  namespace: app-oint
  labels:
    app: app-oint
    component: admin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-oint-admin
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600  # Admin panel can scale down slower
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      selectPolicy: Min

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-oint-business-hpa
  namespace: app-oint
  labels:
    app: app-oint
    component: business
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-oint-business
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      selectPolicy: Min

---
# Custom HPA for Redis (if using Redis cluster)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-oint-redis-hpa
  namespace: app-oint
  labels:
    app: app-oint
    component: redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-oint-redis
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # Redis scaling should be more conservative
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Min
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600
      selectPolicy: Min