name: appoint-$region
region: $region
services:
  - name: api
    source_dir: /functions
    github:
      repo: your-username/appoint
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 2
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health/liveness
      initial_delay_seconds: 10
      interval_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      unhealthy_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: REGION
        value: $region
      - key: DATABASE_URL
        value: \${DATABASE_URL_${region^^}}
      - key: REDIS_URL
        value: \${REDIS_URL_${region^^}}
    autoscaling:
      min_instance_count: 2
      max_instance_count: 10
      cpu_percent: 80
      memory_percent: 75
  - name: web
    source_dir: /web
    github:
      repo: your-username/appoint
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 2
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      initial_delay_seconds: 10
      interval_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      unhealthy_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: REGION
        value: $region
      - key: API_URL
        value: https://api-$region.appoint.com
    autoscaling:
      min_instance_count: 2
      max_instance_count: 10
      cpu_percent: 80
      memory_percent: 75
databases:
  - name: appoint-db-$region
    engine: pg
    version: "15"
    size: db-s-1vcpu-1gb
    region: $region
    maintenance_window:
      day: sunday
      hour: 02:00:00
    backup_restore:
      database_name: appoint
      backup_name: appoint-backup
