// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArWmfe8kSNXX_BXlBoltXFfrE08ujPdI',
    appId: '1:944776470711:web:6f3c833ef110bca6c66d32',
    messagingSenderId: '944776470711',
    projectId: 'app-oint-core',
    authDomain: 'app-oint-core.firebaseapp.com',
    storageBucket: 'app-oint-core.firebasestorage.app',
    measurementId: 'G-HHH7T7JFHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB93HTXwFbJOcBCCpmNrx6yfLrpYq-Ehk',
    appId: '1:944776470711:android:f0e7c50f8f9d4f5dc66d32',
    messagingSenderId: '944776470711',
    projectId: 'app-oint-core',
    storageBucket: 'app-oint-core.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_-DJAUqQDCUgtKH6F3klIWxzYmT5DYY',
    appId: '1:944776470711:ios:b003859c2f8efb38c66d32',
    messagingSenderId: '944776470711',
    projectId: 'app-oint-core',
    storageBucket: 'app-oint-core.firebasestorage.app',
    iosClientId:
        '944776470711-gesa0ohpcjc72ts15doeih54klglqij0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appoint',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_-DJAUqQDCUgtKH6F3klIWxzYmT5DYY',
    appId: '1:944776470711:ios:b003859c2f8efb38c66d32',
    messagingSenderId: '944776470711',
    projectId: 'app-oint-core',
    storageBucket: 'app-oint-core.firebasestorage.app',
    iosClientId:
        '944776470711-gesa0ohpcjc72ts15doeih54klglqij0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDcGvXeU9AOM2WQmulLsfxdhPYZN2d1b0',
    appId: '1:944776470711:web:d22114faaef21badc66d32',
    messagingSenderId: '944776470711',
    projectId: 'app-oint-core',
    authDomain: 'app-oint-core.firebaseapp.com',
    storageBucket: 'app-oint-core.firebasestorage.app',
    measurementId: 'G-QR67RQH24Z',
  );
}
