name: app-oint-admin
services:
  - name: admin
    github:
      repo: "gabriellagziel/appoint"
      branch: main
      source_dir: "admin"
    environment_slug: node-js
    run_command: "npm run start"
    build_command: "npm install && npm run build"
    routes:
      - path: /admin
 