# This configuration completely disables all analysis
analyzer:
  exclude:
    - "**/*.dart"
  
  errors:
    # Disable all rules
    invalid_annotation_target: ignore
    missing_required_param: ignore
    missing_return: ignore
    todo: ignore
    deprecated_member_use: ignore
    public_member_api_docs: ignore
    avoid_final_parameters: ignore
    REDACTED_TOKEN: ignore
    lines_longer_than_80_chars: ignore
    sort_pub_dependencies: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    prefer_final_fields: ignore
    prefer_final_locals: ignore
    unnecessary_const: ignore
    unnecessary_new: ignore
    REDACTED_TOKEN: ignore
    unnecessary_statements: ignore
    avoid_print: ignore
    avoid_empty_else: ignore
    REDACTED_TOKEN: ignore
    await_only_futures: ignore
    camel_case_types: ignore
    cancel_subscriptions: ignore
    close_sinks: ignore
    comment_references: ignore
    control_flow_in_finally: ignore
    directives_ordering: ignore
    empty_catches: ignore
    empty_constructor_bodies: ignore
    empty_statements: ignore
    hash_and_equals: ignore
    implementation_imports: ignore
    library_names: ignore
    library_prefixes: ignore
    non_constant_identifier_names: ignore
    package_names: ignore
    package_prefixed_library_names: ignore
    prefer_contains: ignore
    prefer_equal_for_default_values: ignore
    prefer_initializing_formals: ignore
    prefer_is_empty: ignore
    prefer_is_not_empty: ignore
    REDACTED_TOKEN: ignore
    slash_for_doc_comments: ignore
    test_types_in_equals: ignore
    throw_in_finally: ignore
    type_init_formals: ignore
    REDACTED_TOKEN: ignore
    unnecessary_getters_setters: ignore
    unrelated_type_equality_checks: ignore
    use_rethrow_when_possible: ignore
    valid_regexps: ignore
    always_declare_return_types: ignore
    always_use_package_imports: ignore
    avoid_annotating_with_dynamic: ignore
    REDACTED_TOKEN: ignore
    avoid_catching_errors: ignore
    avoid_double_and_int_checks: ignore
    REDACTED_TOKEN: ignore
    avoid_escaping_inner_quotes: ignore
    REDACTED_TOKEN: ignore
    avoid_implementing_value_types: ignore
    avoid_init_to_null: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    avoid_private_typedef_functions: ignore
    avoid_redundant_argument_values: ignore
    avoid_relative_lib_imports: ignore
    avoid_return_types_on_setters: ignore
    avoid_returning_null_for_future: ignore
    avoid_returning_null_for_void: ignore
    avoid_returning_this: ignore
    avoid_setters_without_getters: ignore
    avoid_shadowing_type_parameters: ignore
    REDACTED_TOKEN: ignore
    avoid_type_to_string: ignore
    avoid_types_as_parameter_names: ignore
    avoid_unnecessary_containers: ignore
    avoid_void_async: ignore
    camel_case_extensions: ignore
    cascade_invocations: ignore
    cast_nullable_to_non_nullable: ignore
    constant_identifier_names: ignore
    REDACTED_TOKEN: ignore
    depend_on_referenced_packages: ignore
    deprecated_consistency: ignore
    exhaustive_cases: ignore
    file_names: ignore
    flutter_style_todos: ignore
    join_return_with_assignment: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    lines_longer_than_80_chars: ignore
    REDACTED_TOKEN: ignore
    no_adjacent_strings_in_list: ignore
    no_duplicate_case_values: ignore
    no_logic_in_create_state: ignore
    no_runtimeType_toString: ignore
    REDACTED_TOKEN: ignore
    null_closures: ignore
    omit_local_variable_types: ignore
    one_member_abstracts: ignore
    only_throw_errors: ignore
    overridden_fields: ignore
    parameter_assignments: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    prefer_asserts_with_message: ignore
    prefer_collection_literals: ignore
    prefer_conditional_assignment: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    prefer_final_in_for_each: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    prefer_if_null_operators: ignore
    prefer_inlined_adds: ignore
    prefer_int_literals: ignore
    REDACTED_TOKEN: ignore
    prefer_is_not_operator: ignore
    prefer_iterable_whereType: ignore
    prefer_mixin: ignore
    prefer_null_aware_operators: ignore
    prefer_single_quotes: ignore
    prefer_spread_collections: ignore
    provide_deprecation_message: ignore
    recursive_getters: ignore
    require_trailing_commas: ignore
    sized_box_for_whitespace: ignore
    sort_child_properties_last: ignore
    sort_constructors_first: ignore
    sort_unnamed_constructors_first: ignore
    type_annotate_public_apis: ignore
    unawaited_futures: ignore
    unnecessary_await_in_return: ignore
    unnecessary_lambdas: ignore
    unnecessary_late: ignore
    unnecessary_null_checks: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    unnecessary_overrides: ignore
    unnecessary_parenthesis: ignore
    unnecessary_raw_strings: ignore
    unnecessary_string_escapes: ignore
    REDACTED_TOKEN: ignore
    unnecessary_this: ignore
    unused_import: ignore
    unused_local_variable: ignore
    REDACTED_TOKEN: ignore
    undefined_function: ignore
    undefined_class: ignore
    undefined_identifier: ignore
    undefined_named_parameter: ignore
    undefined_getter: ignore
    uri_does_not_exist: ignore
    missing_required_argument: ignore
    argument_type_not_assignable: ignore
    unchecked_use_of_nullable_value: ignore
    ambiguous_import: ignore
    REDACTED_TOKEN: ignore
    REDACTED_TOKEN: ignore
    subtype_of_sealed_class: ignore

linter:
  rules: [] 