analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "android/**"
    - "ios/**"
    - "build/**"
    - "test_driver/**"
    - "web/**"
    - "linux/**"
    - "macos/**"
    - "windows/**"
    - "integration_test/**"
    - "test/**"
    - "packages/**"
    - "admin/**"
    - "marketing/**"
    - "dashboard/**"
    - "functions/**"
    - "default/**"
    - "node_modules/**"
    - ".next/**"
    - "out/**"
    - "dist/**"
    - "coverage/**"
    - "docs/**"
    - "scripts/**"
    - "tools/**"
    - "tool/**"
    - "ml/**"
    - "analytics/**"
    - "performance/**"
    - "monitoring/**"
    - "reporting/**"
    - "security/**"
    - "self_healing/**"
    - "flaky_detection/**"
    - "test_data_generation/**"
    - "fastlane/**"
    - "production/**"
    - "accessibility/**"
    - "diagnostics/**"
    - "integrations/**"
    - "config/**"
    - "marketing/**"
    - "admin/**"
    - "dashboard/**"
  
  errors:
    # Only keep the most critical errors
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use: ignore
    public_member_api_docs: ignore
    avoid_final_parameters: ignore
    avoid_catches_without_on_clauses: ignore
    lines_longer_than_80_chars: ignore
    sort_pub_dependencies: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    prefer_final_fields: ignore
    prefer_final_locals: ignore
    unnecessary_const: ignore
    unnecessary_new: ignore
    unnecessary_null_aware_assignments: ignore
    unnecessary_statements: ignore
    avoid_print: ignore
    avoid_empty_else: ignore
    avoid_unused_constructor_parameters: ignore
    await_only_futures: ignore
    camel_case_types: ignore
    cancel_subscriptions: ignore
    close_sinks: ignore
    comment_references: ignore
    control_flow_in_finally: ignore
    directives_ordering: ignore
    empty_catches: ignore
    empty_constructor_bodies: ignore
    empty_statements: ignore
    hash_and_equals: ignore
    implementation_imports: ignore
    library_names: ignore
    library_prefixes: ignore
    non_constant_identifier_names: ignore
    package_names: ignore
    package_prefixed_library_names: ignore
    prefer_contains: ignore
    prefer_equal_for_default_values: ignore
    prefer_initializing_formals: ignore
    prefer_is_empty: ignore
    prefer_is_not_empty: ignore
    prefer_typing_uninitialized_variables: ignore
    slash_for_doc_comments: ignore
    test_types_in_equals: ignore
    throw_in_finally: ignore
    type_init_formals: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_getters_setters: ignore
    unrelated_type_equality_checks: ignore
    use_rethrow_when_possible: ignore
    valid_regexps: ignore

linter:
  rules:
    # Only keep the most essential rules
    - always_declare_return_types
    - camel_case_types
    - directives_ordering
    - library_names
    - package_names
    - slash_for_doc_comments
    - test_types_in_equals
    - type_init_formals
    - valid_regexps 