analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/node_modules/**"
    - "**/coverage/**"
    - "**/test/generated/**"
  
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use: ignore

linter:
  rules:
    # Only essential rules
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - sort_child_properties_last
    - sort_constructors_first
    - use_key_in_widget_constructors 