name: App-Oint
services:
  - name: marketing
    source_dir: marketing
    github:
      repo: saharmor/app-oint
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8080"
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: "0.0.0.0"
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 20
      timeout_seconds: 15
      success_threshold: 1
      failure_threshold: 5
  - name: business
    source_dir: business
    github:
      repo: saharmor/app-oint
      branch: main
    dockerfile_path: business/Dockerfile
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /business
      - path: /business/*
    health_check:
      http_path: /business
      initial_delay_seconds: 90
      period_seconds: 30
      timeout_seconds: 15
      success_threshold: 1
      failure_threshold: 5
  - name: admin
    source_dir: admin
    github:
      repo: saharmor/app-oint
      branch: main
    dockerfile_path: admin/Dockerfile
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /admin
      - path: /admin/*
    health_check:
      http_path: /admin
      initial_delay_seconds: 90
      period_seconds: 30
      timeout_seconds: 15
      success_threshold: 1
      failure_threshold: 5
  - name: api
    source_dir: functions
    github:
      repo: saharmor/app-oint
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8083"
      - key: NODE_ENV
        value: production
    routes:
      - path: /api
      - path: /api/*
    health_check:
      http_path: /api/health
      initial_delay_seconds: 90
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
domains:
  - domain: app-oint.com
    type: PRIMARY
