name: App-Oint
services:
  - name: marketing
    source_dir: marketing
    github:
      repo: saharmor/app-oint
      branch: main
    run_command: npm start
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: NEXT_PUBLIC_API_URL
        value: "https://app-oint.com/api"
    health_check:
      http_path: /
      initial_delay_seconds: 120
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 5
  - name: business
    source_dir: business
    routes:
      - path: /business/*
  - name: admin
    source_dir: admin
    routes:
      - path: /admin/*
  - name: api
    source_dir: functions
    routes:
      - path: /api/*
