name: app-oint
region: fra1
services:
  # === Marketing App ===
  - name: marketing
    source_dir: marketing
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    build_command: npm ci && npm run build
    run_command: npm run start -- -p 3000
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

  # === Business App ===
  - name: business
    source_dir: business
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    build_command: npm ci && npm run build
    run_command: npm run start -- -p 3002
    http_port: 3002
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /business
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3002"

  # === Admin App ===
  - name: admin
    source_dir: admin
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    build_command: npm ci && npm run build
    run_command: npm run start -- -p 3003
    http_port: 3003
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /admin
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3003"

  # === Enterprise App ===
  - name: enterprise
    source_dir: enterprise-app
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    build_command: npm ci && npm run build
    run_command: npm run start -- -p 3001
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /enterprise
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"

  # === Personal (Flutter PWA) ===
  - name: personal
    source_dir: appoint
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    build_command: |
      flutter pub get
      flutter build web --release --web-renderer html
    run_command: npx serve -s build/web -l 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /personal
    health_check:
      http_path: /health.txt
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"

  # === Functions / API ===
  - name: functions
    source_dir: functions
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    build_command: npm ci
    run_command: npx tsx src/server.ts
    http_port: 8088
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    health_check:
      http_path: /api/status
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8088"
