targets:
  $default:
    builders:
      json_serializable:
        options:
          # Configure JSON serialization
          field_rename: snake
          include_if_null: false
        generate_for:
          - lib/models/**.dart
          - lib/features/**/models/**.dart
        enabled: true
      freezed:
        options:
          # Configure Freezed code generation
          union_key: type
          union_value_case: snake
          map: false
          when: true
          copy_with: true
          to_string: true
          equals: true
        generate_for:
          - lib/models/**.dart
          - lib/features/**/models/**.dart
        enabled: true
      # Configure output directory for generated files
      # Note: build_web_compilers is deprecated, using default configuration 