name: app-oint-business
region: nyc1

services:
  - name: business
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "business"
    build_command: "npm ci && npm run build"
    run_command: "npm start"
    http_port: 80
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xxs

# Ingress configuration for routing
ingress:
  rules:
    - match:
        path:
          prefix: "/"
      component:
        name: business

# Domain configuration
domains:
  - domain: business.app-oint.com
    type: PRIMARY
    zone: app-oint.com

# Environment variables
envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "80" 