name: app-oint-consolidated
region: nyc1

services:
  - name: marketing
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "marketing"
    build_command: "npm ci && npm run build"
    run_command: "npm start"
    http_port: 80
    health_check:
      http_path: /
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: business
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "business"
    build_command: "npm ci && npm run build"
    run_command: "npm start"
    http_port: 80
    health_check:
      http_path: /
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: enterprise
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "enterprise-onboarding-portal"
    build_command: "npm ci && npm run build"
    run_command: "npm start"
    http_port: 80
    health_check:
      http_path: /
    instance_count: 1
    instance_size_slug: basic-xxs

# Ingress configuration for routing
ingress:
  rules:
    - match:
        path:
          prefix: "/"
      component:
        name: marketing
    - match:
        path:
          prefix: "/business"
      component:
        name: business
    - match:
        path:
          prefix: "/enterprise"
      component:
        name: enterprise

# Domain configuration
domains:
  - domain: app-oint.com
    type: PRIMARY
    zone: app-oint.com

# Environment variables
envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "80" 