name: appoint-flutter-web
region: nyc
services:
- name: appoint-flutter-web
  source_dir: /
  github:
    repo: appoint
    branch: main
  run_command: npx serve -s build/web -l 8080
  build_command: |
    flutter pub get
    dart run build_runner build --delete-conflicting-outputs
    flutter build web --release --web-renderer html
    echo "✅ Flutter web build completed"
    ls -la build/web/
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /flutter-web
  - path: /flutter-web/*
  envs:
  - key: FLUTTER_VERSION
    value: "3.32.5"
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
  # Use custom Docker image for faster builds
  image:
    registry_type: DOCR
    registry: registry.digitalocean.com
    repository: appoint/flutter-ci
    tag: latest
- name: admin-panel
  environment_slug: node-js
  github:
    repo: "gabriellagziel/appoint-web-only"
    branch: main
  source_dir: "admin"
  build_command: "npm ci && npm run build --prefix admin"
  run_command: "npm start --prefix admin"
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 30
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
    - path: /admin
  envs:
    - key: NODE_ENV
      value: "production"
    - key: PORT
      value: "3000"