name: app-oint-platform
region: nyc1

services:
  # Main Portal Service - Beautiful landing page
  - name: portal
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "marketing"
    build_command: "npm ci && echo 'Creating Fantastic App-Oint Portal...' && cat > pages/_app.js << 'EOF' && export default function App({ Component, pageProps }) { return <Component {...pageProps} /> } && EOF && cat > pages/index.js << 'EOF' && export default function Home() { return ( <div style={{ fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, sans-serif', margin: 0, padding: '0', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', minHeight: '100vh' }}> <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '40px 20px' }}> <header style={{ textAlign: 'center', marginBottom: '60px' }}> <h1 style={{ color: 'white', fontSize: '3.5rem', marginBottom: '15px', fontWeight: '800', textShadow: '0 4px 20px rgba(0,0,0,0.3)' }}>App-Oint</h1> <p style={{ color: 'rgba(255,255,255,0.9)', fontSize: '1.4rem', marginBottom: '10px' }}>Complete Appointment Management Platform</p> <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '1.1rem' }}>Streamline your business with intelligent scheduling</p> </header> <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '30px', marginBottom: '50px' }}> <div style={{ background: 'rgba(255,255,255,0.95)', padding: '40px', borderRadius: '16px', boxShadow: '0 8px 32px rgba(0,0,0,0.1)', border: '1px solid rgba(255,255,255,0.2)', backdropFilter: 'blur(10px)' }}> <div style={{ display: 'flex', alignItems: 'center', marginBottom: '20px' }}> <div style={{ background: '#007bff', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '15px' }}> <span style={{ fontSize: '24px' }}>🏢</span> </div> <h2 style={{ color: '#2c3e50', margin: '0', fontSize: '1.8rem', fontWeight: '700' }}>Business</h2> </div> <p style={{ color: '#6c757d', marginBottom: '25px', lineHeight: '1.6', fontSize: '1.1rem' }}>Complete business management solution with appointment scheduling, customer management, analytics, and automated workflows.</p> <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}> <a href='https://business.app-oint.com' style={{ display: 'inline-block', background: '#007bff', color: 'white', padding: '12px 24px', borderRadius: '8px', textDecoration: 'none', fontWeight: '600', transition: 'all 0.3s ease', boxShadow: '0 4px 15px rgba(0,123,255,0.3)' }}>Access Portal</a> <span style={{ background: '#e9ecef', color: '#6c757d', padding: '8px 12px', borderRadius: '6px', fontSize: '0.9rem' }}>Live</span> </div> </div> <div style={{ background: 'rgba(255,255,255,0.95)', padding: '40px', borderRadius: '16px', boxShadow: '0 8px 32px rgba(0,0,0,0.1)', border: '1px solid rgba(255,255,255,0.2)', backdropFilter: 'blur(10px)' }}> <div style={{ display: 'flex', alignItems: 'center', marginBottom: '20px' }}> <div style={{ background: '#28a745', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '15px' }}> <span style={{ fontSize: '24px' }}>🏢</span> </div> <h2 style={{ color: '#2c3e50', margin: '0', fontSize: '1.8rem', fontWeight: '700' }}>Enterprise</h2> </div> <p style={{ color: '#6c757d', marginBottom: '25px', lineHeight: '1.6', fontSize: '1.1rem' }}>Advanced enterprise features with multi-location support, advanced reporting, custom integrations, and white-label solutions.</p> <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}> <a href='https://enterprise.app-oint.com' style={{ display: 'inline-block', background: '#28a745', color: 'white', padding: '12px 24px', borderRadius: '8px', textDecoration: 'none', fontWeight: '600', transition: 'all 0.3s ease', boxShadow: '0 4px 15px rgba(40,167,69,0.3)' }}>Access Portal</a> <span style={{ background: '#e9ecef', color: '#6c757d', padding: '8px 12px', borderRadius: '6px', fontSize: '0.9rem' }}>Live</span> </div> </div> <div style={{ background: 'rgba(255,255,255,0.95)', padding: '40px', borderRadius: '16px', boxShadow: '0 8px 32px rgba(0,0,0,0.1)', border: '1px solid rgba(255,255,255,0.2)', backdropFilter: 'blur(10px)' }}> <div style={{ display: 'flex', alignItems: 'center', marginBottom: '20px' }}> <div style={{ background: '#6f42c1', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '15px' }}> <span style={{ fontSize: '24px' }}>📱</span> </div> <h2 style={{ color: '#2c3e50', margin: '0', fontSize: '1.8rem', fontWeight: '700' }}>Mobile Apps</h2> </div> <p style={{ color: '#6c757d', marginBottom: '25px', lineHeight: '1.6', fontSize: '1.1rem' }}>Native Flutter mobile applications for iOS and Android with offline capabilities, push notifications, and seamless API integration.</p> <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}> <a href='/mobile' style={{ display: 'inline-block', background: '#6f42c1', color: 'white', padding: '12px 24px', borderRadius: '8px', textDecoration: 'none', fontWeight: '600', transition: 'all 0.3s ease', boxShadow: '0 4px 15px rgba(111,66,193,0.3)' }}>Download Apps</a> <span style={{ background: '#e9ecef', color: '#6c757d', padding: '8px 12px', borderRadius: '6px', fontSize: '0.9rem' }}>Live</span> </div> </div> <div style={{ background: 'rgba(255,255,255,0.95)', padding: '40px', borderRadius: '16px', boxShadow: '0 8px 32px rgba(0,0,0,0.1)', border: '1px solid rgba(255,255,255,0.2)', backdropFilter: 'blur(10px)' }}> <div style={{ display: 'flex', alignItems: 'center', marginBottom: '20px' }}> <div style={{ background: '#dc3545', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '15px' }}> <span style={{ fontSize: '24px' }}>⚙️</span> </div> <h2 style={{ color: '#2c3e50', margin: '0', fontSize: '1.8rem', fontWeight: '700' }}>System Admin</h2> </div> <p style={{ color: '#6c757d', marginBottom: '25px', lineHeight: '1.6', fontSize: '1.1rem' }}>Administrative tools for system management, user administration, platform configuration, and advanced monitoring.</p> <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}> <a href='/admin' style={{ display: 'inline-block', background: '#dc3545', color: 'white', padding: '12px 24px', borderRadius: '8px', textDecoration: 'none', fontWeight: '600', transition: 'all 0.3s ease', boxShadow: '0 4px 15px rgba(220,53,69,0.3)' }}>Admin Panel</a> <span style={{ background: '#e9ecef', color: '#6c757d', padding: '8px 12px', borderRadius: '6px', fontSize: '0.9rem' }}>Live</span> </div> </div> </div> <div style={{ background: 'rgba(255,255,255,0.1)', padding: '30px', borderRadius: '16px', textAlign: 'center', marginTop: '40px' }}> <h3 style={{ color: 'white', marginBottom: '15px', fontSize: '1.5rem' }}>🚀 Why Choose App-Oint?</h3> <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', marginTop: '20px' }}> <div style={{ color: 'rgba(255,255,255,0.9)' }}> <strong>⚡ Lightning Fast</strong><br/> <span style={{ fontSize: '0.9rem' }}>Optimized for speed</span> </div> <div style={{ color: 'rgba(255,255,255,0.9)' }}> <strong>🔒 Enterprise Security</strong><br/> <span style={{ fontSize: '0.9rem' }}>Bank-level protection</span> </div> <div style={{ color: 'rgba(255,255,255,0.9)' }}> <strong>📊 Advanced Analytics</strong><br/> <span style={{ fontSize: '0.9rem' }}>Deep insights</span> </div> <div style={{ color: 'rgba(255,255,255,0.9)' }}> <strong>🌐 Global Scale</strong><br/> <span style={{ fontSize: '0.9rem' }}>Worldwide deployment</span> </div> </div> </div> <footer style={{ textAlign: 'center', padding: '40px 0', color: 'rgba(255,255,255,0.7)', marginTop: '60px' }}> <p style={{ marginBottom: '10px' }}>© 2025 App-Oint. All rights reserved.</p> <p style={{ fontSize: '0.9rem' }}>Built with ❤️ for modern businesses</p> </footer> </div> </div> ) } && EOF && mv tsconfig.json tsconfig.json.backup 2>/dev/null || true && NEXT_TELEMETRY_DISABLED=1 npx next build --no-lint"
    run_command: "npm start"
    http_port: 80
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xxs

  # Admin Service - Your existing admin panel
  - name: admin
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "admin"
    build_command: "npm ci && npm run build"
    run_command: "npm start"
    http_port: 3000
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xxs

  # Mobile Service - Mobile app download page
  - name: mobile
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "mobile"
    build_command: "npm ci && echo 'Mobile app download page built successfully'"
    run_command: "npx serve public -p 80"
    http_port: 80
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xxs

# Advanced Ingress Configuration
ingress:
  rules:
    # Main portal - app-oint.com
    - match:
        path:
          prefix: "/"
      component:
        name: portal
    
    # Admin service - app-oint.com/admin
    - match:
        path:
          prefix: "/admin"
      component:
        name: admin

    # Mobile service - app-oint.com/mobile
    - match:
        path:
          prefix: "/mobile"
      component:
        name: mobile

# Domain Configuration
domains:
  - domain: app-oint.com
    type: PRIMARY
    zone: app-oint.com

# Environment Variables
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "80"
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
    scope: RUN_AND_BUILD_TIME
  - key: NPM_CONFIG_CACHE
    value: ".npm-cache"
    scope: RUN_AND_BUILD_TIME
  - key: PLATFORM_ENV
    value: "production"
    scope: RUN_AND_BUILD_TIME 