name: appoint-app-v2
region: fra1
features:
  - buildpack-stack=ubuntu-22

services:
  - name: api
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "functions"
    build_command: "rm -rf .next && npm install && npm run build"
    run_command: "npm run start"
    http_port: 8080
    routes:
      - path: /api

  - name: admin
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "admin"
    build_command: "rm -rf .next && npm install && npm run build"
    run_command: "npm start"
    http_port: 3000
    routes:
      - path: /admin

  - name: dashboard
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "dashboard"
    build_command: "rm -rf .next && npm install && npm run build"
    run_command: "npm start"
    http_port: 3000
    routes:
      - path: /dashboard

  - name: business
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "business"
    build_command: "npm ci && npm run build && npm run export"
    run_command: "npm run start"
    http_port: 8081
    routes:
      - path: /business
        preserve_path_prefix: true
    health_check:
      http_path: /business
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

  - name: marketing
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "marketing"
    build_command: "rm -rf .next out && npm install && npm run build"
    run_command: "npm start"
    http_port: 3000
    routes:
      - path: /

domains:
  - domain: app-oint.com
    type: PRIMARY
    zone: app-oint.com