name: App-Oint
services:
  - name: marketing
    source_dir: marketing
    github:
      repo: gabriellagziel/appoint
      branch: main
    build_command: chmod +x build-deploy.sh && ./build-deploy.sh
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8080"
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NPM_CONFIG_CACHE
        value: ".npm-cache"
    routes:
      - path: "/"
    health_check:
      http_path: /
      initial_delay_seconds: 120
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
domains:
  - domain: app-oint.com
    type: PRIMARY