# Mobile App Configuration for App-Oint Platform
# This shows how the Flutter mobile app connects to your platform

mobile_app:
  name: "App-Oint Mobile"
  platform: "Flutter"
  version: "1.0.0"
  
  # API Endpoints Configuration
  api_endpoints:
    # Business Service API
    business_api:
      base_url: "https://business.app-oint.com/api"
      endpoints:
        - "/appointments"
        - "/customers"
        - "/analytics"
        - "/payments"
    
    # Enterprise Service API  
    enterprise_api:
      base_url: "https://enterprise.app-oint.com/api"
      endpoints:
        - "/multi-location"
        - "/advanced-analytics"
        - "/white-label"
        - "/integrations"
    
    # Admin Service API
    admin_api:
      base_url: "https://app-oint.com/admin/api"
      endpoints:
        - "/users"
        - "/system-config"
        - "/monitoring"
        - "/reports"

  # Mobile App Services
  services:
    - name: "Authentication"
      file: "lib/services/auth_service.dart"
      connects_to: "business_api, enterprise_api"
    
    - name: "Appointments"
      file: "lib/services/appointment_service.dart"
      connects_to: "business_api"
    
    - name: "Business Management"
      file: "lib/services/business_service.dart"
      connects_to: "business_api"
    
    - name: "Enterprise Features"
      file: "lib/services/enterprise_service.dart"
      connects_to: "enterprise_api"
    
    - name: "Payments"
      file: "lib/services/payment_service.dart"
      connects_to: "business_api, enterprise_api"
    
    - name: "Notifications"
      file: "lib/services/notification_service.dart"
      connects_to: "business_api, enterprise_api"
    
    - name: "Analytics"
      file: "lib/services/analytics_service.dart"
      connects_to: "business_api, enterprise_api"
    
    - name: "Admin Panel"
      file: "lib/services/admin_service.dart"
      connects_to: "admin_api"

  # Connection Security
  security:
    ssl_pinning: true
    certificate_pinning: "lib/services/certificate_pinning_service.dart"
    api_key_authentication: true
    jwt_tokens: true
    
  # Offline Capabilities
  offline_features:
    - "Offline appointment booking"
    - "Local data caching"
    - "Sync when online"
    - "Offline repository": "lib/services/offline_booking_repository.dart"

  # Push Notifications
  notifications:
    fcm_service: "lib/services/fcm_service.dart"
    local_notifications: "lib/services/local_notification_service.dart"
    deep_linking: "lib/services/custom_deep_link_service.dart"

# Deployment Configuration
deployment:
  # iOS App Store
  ios:
    bundle_id: "com.appoint.mobile"
    app_store_connect: true
    
  # Google Play Store  
  android:
    package_name: "com.appoint.mobile"
    google_play_console: true
    
  # Internal Testing
  internal:
    firebase_app_distribution: true
    testflight: true
    google_play_internal_testing: true 