name: app-oint-platform
region: nyc1

services:
  # Main Portal Service - Using existing marketing setup
  - name: portal
    environment_slug: node-js
    github:
      repo: "gabriellagziel/appoint"
      branch: main
    source_dir: "marketing"
    build_command: "npm ci"
    run_command: "npx serve public -p 3000"
    http_port: 3000
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xxs

# Domain Configuration
domains:
  - domain: app-oint.com
    type: PRIMARY
    zone: app-oint.com

# Environment Variables
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "3000"
    scope: RUN_AND_BUILD_TIME 