name: appoint
description: "Appointment management application"
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_riverpod: ^2.4.9
  provider: ^6.1.2
  
  # Firebase (pinned to web-stable versions)
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.5
  firebase_remote_config: ^4.3.18
  firebase_app_check: ^0.2.2+1
  # firebase_storage removed for web-run stability; re-enable for mobile if needed
  # firebase_storage: ^11.6.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  crypto: ^3.0.0
  
  # WebView for ads
  webview_flutter: ^4.4.2
  
  # HTTP for API calls
  http: ^1.1.0
  
  # URL launcher for payment links
  url_launcher: ^6.2.2
  
  # Maps and navigation
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  qr_flutter: ^4.1.0
  go_router: ^12.1.3
  # ensure go_router is available at or above 14.2.0 if desired
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Firebase messaging for push notifications
  # firebase_messaging removed for web-run stability; re-enable for mobile if needed
  # firebase_messaging: ^14.9.4
  # Web plugin compatibility pins (to avoid handleThenable/jsify issues)
dependency_overrides:
  firebase_auth_web: ^5.12.0
  firebase_core_web: ^2.17.5
  cloud_firestore_web: ^3.12.5
  # web variants disabled alongside deps above
  # firebase_storage_web: ^3.9.7
  # firebase_messaging_web: ^3.8.7
  _flutterfire_internals: ^1.3.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - l10n/


