#!/bin/bash
echo "🔍 DEAD CODE DETECTION STARTING..."
echo "====================================="
REPORT_FILE="dead_code_report_$(date +%Y%m%d_%H%M%S).txt"
echo "Finding Dart files without imports..."
find . -name "*.dart" | xargs grep -L "import" | grep -v "test_driver" | grep -v "integration_test" | grep -v "test/" | grep -v "generated" > "$REPORT_FILE"
echo "Finding Dart files without classes/enums..."
find . -name "*.dart" | xargs grep -L "class\|enum\|typedef" | grep -v "test_driver" | grep -v "integration_test" | grep -v "test/" >> "$REPORT_FILE"
echo "Finding TODO/FIXME comments..."
find . -name "*.dart" -o -name "*.js" -o -name "*.ts" | grep -v node_modules | xargs grep -l "TODO\|FIXME\|XXX\|HACK" >> "$REPORT_FILE"
echo "✅ DEAD CODE DETECTION COMPLETE!"
echo "📊 Report saved to: $REPORT_FILE"
