#!/bin/bash
echo "🎯 PERFECT CODEBASE AUDIT STARTING..."
echo "========================================="
AUDIT_REPORT="perfect_codebase_audit_$(date +%Y%m%d_%H%M%S).txt"
{
    echo "🎯 PERFECT CODEBASE AUDIT REPORT"
    echo "====================================="
    echo "Date: $(date)"
    echo ""
    echo "📊 CODEBASE STATISTICS"
    echo "Total Dart files: $(find . -name "*.dart" | wc -l)"
    echo "Total JavaScript files: $(find . -name "*.js" | wc -l)"
    echo "Total TypeScript files: $(find . -name "*.ts" | wc -l)"
    echo "Total HTML files: $(find . -name "*.html" | wc -l)"
    echo "Total Python files: $(find . -name "*.py" | wc -l)"
    echo ""
    echo "🚨 ISSUES FOUND"
    echo "Temporary files: $(find . -name "*.tmp" -o -name "*.backup" -o -name "*.old" -o -name "*~" | wc -l)"
    echo "Node modules directories: $(find . -name "node_modules" -type d | wc -l)"
    echo "Dart files without imports: $(find . -name "*.dart" | xargs grep -L "import" | grep -v "test_driver" | grep -v "integration_test" | grep -v "test/" | grep -v "generated" | wc -l)"
    echo "Dart files without classes: $(find . -name "*.dart" | xargs grep -L "class\|enum\|typedef" | grep -v "test_driver" | grep -v "integration_test" | grep -v "test/" | wc -l)"
    echo "Files with TODO/FIXME: $(find . -name "*.dart" -o -name "*.js" -o -name "*.ts" | grep -v node_modules | xargs grep -l "TODO\|FIXME\|XXX\|HACK" 2>/dev/null | wc -l)"
    echo ""
    echo "🔧 RECOMMENDATIONS"
    echo "1. Run comprehensive cleanup script"
    echo "2. Run link validation script"
    echo "3. Run dead code detection script"
    echo "4. Review and fix TODO/FIXME items"
    echo "5. Organize file structure"
} > "$AUDIT_REPORT"
echo "✅ PERFECT CODEBASE AUDIT COMPLETE!"
echo "📊 Report saved to: $AUDIT_REPORT"
