/// Extension providing fallback English strings for newly–added admin/broadcast UI
/// keys that have not yet been added to the autogenerated AppLocalizations files.
///
/// This keeps the build passing until the ARB template and code-gen pipeline are
/// updated. When the official localization files are regenerated, this file can
/// be removed.
// ignore_for_file: type=lint

import 'app_localizations.dart';

extension AppLocalizationsAdminExt on AppLocalizations {
  // ----- Form labels / validation -----
  String get title => 'Title';
  String get messageType => 'Message Type';
  String get externalLink => 'External Link';
  String get option => 'Option';

  // Validation messages
  String get pleaseEnterTitle => 'Please enter a title';
  String get pleaseEnterContent => 'Please enter the content';
  String get pleaseEnterLink => 'Please enter a link';

  // Media section
  String get imageSelected => 'Image selected';
  String get videoSelected => 'Video selected';
  String get image => 'Image';
  String get video => 'Video';
  String get failedToUploadImage => 'Failed to upload image';
  String get failedToUploadVideo => 'Failed to upload video';
  String get errorPickingImage => 'Error picking image';
  String get errorPickingVideo => 'Error picking video';

  // Targeting / audience filters
  String get targetingFilters => 'Targeting Filters';
  String get countries => 'Countries';
  String get cities => 'Cities';
  String get subscriptionTiers => 'Subscription Tiers';
  String get userRoles => 'User Roles';
  String get estimatedRecipients => 'Estimated Recipients';

  // Scheduling
  String get scheduling => 'Scheduling';
  String get scheduleForLater => 'Schedule for Later';

  // Errors / misc
  String get errorEstimatingRecipients => 'Error estimating recipients';
  String get userNotAuthenticated => 'User not authenticated';

  // Polls
  String get pollOptions => 'Poll Options';
}