name: Validate Secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly validation
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate Firebase Secrets
        run: |
          echo "🔍 Validating Firebase secrets..."
          
          if [ -n "${{ secrets.FIREBASE_TOKEN }}" ]; then
            echo "✅ FIREBASE_TOKEN is set"
          else
            echo "❌ FIREBASE_TOKEN is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.FIREBASE_PROJECT_ID }}" ]; then
            echo "✅ FIREBASE_PROJECT_ID is set"
          else
            echo "❌ FIREBASE_PROJECT_ID is missing"
            exit 1
          fi
          
          echo "✅ Firebase secrets validation passed"
          
      - name: Validate Android Secrets
        run: |
          echo "🔍 Validating Android secrets..."
          
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "✅ ANDROID_KEYSTORE_BASE64 is set"
          else
            echo "❌ ANDROID_KEYSTORE_BASE64 is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" ]; then
            echo "✅ ANDROID_KEYSTORE_PASSWORD is set"
          else
            echo "❌ ANDROID_KEYSTORE_PASSWORD is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.ANDROID_KEY_ALIAS }}" ]; then
            echo "✅ ANDROID_KEY_ALIAS is set"
          else
            echo "❌ ANDROID_KEY_ALIAS is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.ANDROID_KEY_PASSWORD }}" ]; then
            echo "✅ ANDROID_KEY_PASSWORD is set"
          else
            echo "❌ ANDROID_KEY_PASSWORD is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.PLAY_STORE_JSON_KEY }}" ]; then
            echo "✅ PLAY_STORE_JSON_KEY is set"
          else
            echo "❌ PLAY_STORE_JSON_KEY is missing"
            exit 1
          fi
          
          echo "✅ Android secrets validation passed"
          
      - name: Validate iOS Secrets
        run: |
          echo "🔍 Validating iOS secrets..."
          
          if [ -n "${{ secrets.IOS_P12_CERTIFICATE }}" ]; then
            echo "✅ IOS_P12_CERTIFICATE is set"
          else
            echo "❌ IOS_P12_CERTIFICATE is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.IOS_P12_PASSWORD }}" ]; then
            echo "✅ IOS_P12_PASSWORD is set"
          else
            echo "❌ IOS_P12_PASSWORD is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.APPLE_ISSUER_ID }}" ]; then
            echo "✅ APPLE_ISSUER_ID is set"
          else
            echo "❌ APPLE_ISSUER_ID is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.APPLE_API_KEY_ID }}" ]; then
            echo "✅ APPLE_API_KEY_ID is set"
          else
            echo "❌ APPLE_API_KEY_ID is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.APPLE_API_PRIVATE_KEY }}" ]; then
            echo "✅ APPLE_API_PRIVATE_KEY is set"
          else
            echo "❌ APPLE_API_PRIVATE_KEY is missing"
            exit 1
          fi
          
          echo "✅ iOS secrets validation passed"
          
      - name: Validate DigitalOcean Secrets
        run: |
          echo "🔍 Validating DigitalOcean secrets..."
          
          if [ -n "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" ]; then
            echo "✅ DIGITALOCEAN_ACCESS_TOKEN is set"
          else
            echo "❌ DIGITALOCEAN_ACCESS_TOKEN is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.DIGITALOCEAN_APP_ID }}" ]; then
            echo "✅ DIGITALOCEAN_APP_ID is set"
          else
            echo "❌ DIGITALOCEAN_APP_ID is missing"
            exit 1
          fi
          
          echo "✅ DigitalOcean secrets validation passed"
          
      - name: Validate Notification Secrets
        run: |
          echo "🔍 Validating notification secrets..."
          
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "✅ SLACK_WEBHOOK_URL is set"
          else
            echo "⚠️ SLACK_WEBHOOK_URL is missing (optional)"
          fi
          
          if [ -n "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "✅ DISCORD_WEBHOOK is set"
          else
            echo "⚠️ DISCORD_WEBHOOK is missing (optional)"
          fi
          
          echo "✅ Notification secrets validation passed"
          
      - name: Validate Stripe Secrets
        run: |
          echo "🔍 Validating Stripe secrets..."
          
          if [ -n "${{ secrets.STRIPE_PUBLISHABLE_KEY }}" ]; then
            echo "✅ STRIPE_PUBLISHABLE_KEY is set"
          else
            echo "❌ STRIPE_PUBLISHABLE_KEY is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.STRIPE_SECRET_KEY }}" ]; then
            echo "✅ STRIPE_SECRET_KEY is set"
          else
            echo "❌ STRIPE_SECRET_KEY is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.STRIPE_WEBHOOK_SECRET }}" ]; then
            echo "✅ STRIPE_WEBHOOK_SECRET is set"
          else
            echo "❌ STRIPE_WEBHOOK_SECRET is missing"
            exit 1
          fi
          
          echo "✅ Stripe secrets validation passed"
          
      - name: Validate Analytics Secrets
        run: |
          echo "🔍 Validating analytics secrets..."
          
          if [ -n "${{ secrets.SENTRY_DSN }}" ]; then
            echo "✅ SENTRY_DSN is set"
          else
            echo "⚠️ SENTRY_DSN is missing (optional)"
          fi
          
          if [ -n "${{ secrets.MIXPANEL_TOKEN }}" ]; then
            echo "✅ MIXPANEL_TOKEN is set"
          else
            echo "⚠️ MIXPANEL_TOKEN is missing (optional)"
          fi
          
          echo "✅ Analytics secrets validation passed"
          
      - name: Validate Google Services
        run: |
          echo "🔍 Validating Google services secrets..."
          
          if [ -n "${{ secrets.GOOGLE_CLIENT_ID }}" ]; then
            echo "✅ GOOGLE_CLIENT_ID is set"
          else
            echo "❌ GOOGLE_CLIENT_ID is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.GOOGLE_CLIENT_SECRET }}" ]; then
            echo "✅ GOOGLE_CLIENT_SECRET is set"
          else
            echo "❌ GOOGLE_CLIENT_SECRET is missing"
            exit 1
          fi
          
          echo "✅ Google services validation passed"
          
      - name: Generate Secrets Report
        run: |
          echo "📊 Secrets Validation Report"
          echo "=========================="
          echo "✅ All required secrets are configured"
          echo "✅ CI/CD pipeline should be functional"
          echo "✅ Ready for deployment"
          
      - name: Notify Success
        if: success()
        run: |
          echo "🎉 All secrets validation passed!"
          echo "✅ CI/CD pipeline is properly configured"
          
      - name: Notify Failure
        if: failure()
        run: |
          echo "❌ Secrets validation failed!"
          echo "Please check the missing secrets above"
          echo "Refer to .github/workflows/secrets-management.md for setup instructions"