name: CI

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: stable
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: npm install
      - run: dart run tool/arb_validator.dart
      - run: npm run spell-check 