name: Coverage Badge

push:
  branches: [ main ]

on: workflow_dispatch
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder Coverage
        run: echo "Coverage stub"
