name: Coverage Badge

push:
  branches: [ main ]

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Placeholder Coverage
        run: echo "Coverage stub"