name: Coverage Badge

on:
  push:
    branches: [ main ]
    paths:
      - "appoint/**"
      - "test/**"
      - ".github/workflows/coverage-badge.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "appoint/**"
      - "test/**"
      - ".github/workflows/coverage-badge.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: coverage-badge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          cd appoint
          flutter pub get
          
      - name: Run tests with coverage
        run: |
          cd appoint
          flutter test --coverage
          
      - name: Generate coverage report
        run: |
          cd appoint
          genhtml coverage/lcov.info -o coverage/html
          
      - name: Coverage Badge Complete
        run: echo "✅ Coverage badge generation complete"