name: Deploy Perfect App-oint

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.32.5'
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Install API dependencies
        run: |
          cd dashboard
          npm install
          
      - name: Build Flutter web
        run: |
          flutter build web --release --web-renderer html
          
      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: app-oint-perfect
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Health check after deployment
        run: |
          sleep 30
          curl -f https://app-oint.com/api/health || exit 1
          curl -f https://app-oint.com/ || exit 1
