name: Docker Push to DigitalOcean Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (default: latest)'
        required: false
        default: 'latest'
        type: string

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: appoint/flutter-ci

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/appoint/flutter-ci:${{ github.event.inputs.tag || 'latest' }} .

      - name: Push Docker image
        run: docker push registry.digitalocean.com/appoint/flutter-ci:${{ github.event.inputs.tag || 'latest' }}

      - name: Output image info
        run: |
          echo "Successfully built and pushed image:"
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Image: ${{ env.IMAGE_NAME }}"
          echo "Tag: ${{ github.event.inputs.tag || 'latest' }}"
          echo "Full image name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag || 'latest' }}"