name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v4
        with:
          flutter-version: '3.32.6'
          channel: stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get Flutter dependencies
        run: |
          echo "Installing Flutter dependencies..."
          flutter pub get
          echo "✅ Flutter dependencies installed successfully"

      - name: Generate code (optional)
        run: |
          echo "Running code generation..."
          dart run build_runner build --delete-conflicting-outputs || echo "⚠️ Code generation completed with warnings (continuing)"
        continue-on-error: true

      - name: Build web app
        run: |
          echo "Building Flutter web app..."
          flutter build web --release
          echo "✅ Flutter web build completed successfully"

      - name: Verify build output
        run: |
          echo "Verifying build output..."
          ls -la build/web/
          if [ ! -f "build/web/index.html" ]; then
            echo "❌ Build verification failed: index.html not found"
            exit 1
          fi
          if [ ! -f "build/web/flutter_bootstrap.js" ]; then
            echo "❌ Build verification failed: flutter_bootstrap.js not found"
            exit 1
          fi
          echo "✅ Build verification passed"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ -n "$FIREBASE_TOKEN" ]; then
            echo "Deploying to Firebase Hosting..."
            firebase deploy --only hosting --token "$FIREBASE_TOKEN"
            echo "✅ Firebase deployment completed successfully"
          else
            echo "❌ Firebase token not available, cannot deploy"
            exit 1
          fi