name: iOS Build

on: workflow_dispatch
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder iOS Build
        run: echo "iOS build stub"
