name: L10n Audit

on: [push, pull_request]

jobs:
  l10n_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
      - name: Install deps
        run: flutter pub get
      - name: Run L10n Audit
        run: python3 tools/l10n_audit.py 