name: L10n Check

on:
  push:
    paths:
      - 'lib/l10n/**'
      - '.github/workflows/l10n-check.yml'
      - 'check_translations.py'
  pull_request:
    paths:
      - 'lib/l10n/**'
      - '.github/workflows/l10n-check.yml'
      - 'check_translations.py'

jobs:
  l10n-check:
    name: Translation Completeness Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install jsonschema tabulate
          
      - name: Run translation check
        run: |
          python3 check_translations.py --fail-on-incomplete --threshold 100
          
      - name: Generate detailed report
        run: |
          python3 check_translations.py --output l10n_report.md
          
      - name: Upload translation report
        uses: actions/upload-artifact@v4
        with:
          name: translation-completeness-report
          path: l10n_report.md
          retention-days: 30 