name: L10n Audit

on:
  push:
    paths:
      - "appoint/l10n/**"
      - "appoint/lib/**"
      - "tools/**"
      - ".github/workflows/l10n_audit.yml"
  pull_request:
    paths:
      - "appoint/l10n/**"
      - "appoint/lib/**"
      - "tools/**"
      - ".github/workflows/l10n_audit.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: l10n-audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  l10n_audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
      - name: Install deps
        run: flutter pub get
      - name: Run L10n Audit
        run: python3 tools/l10n_audit.py 