# Test Configuration for CI/CD Pipeline

# This file defines the test configuration for all workflows in the CI/CD pipeline.
# It ensures consistent test execution across all environments and platforms.

test_configuration:
  # Unit Tests
  unit_tests:
    enabled: true
    timeout_minutes: 15
    coverage_threshold: 80
    parallel_jobs: 4
    retry_count: 2
    include_patterns:
      - "test/unit/**/*_test.dart"
      - "test/models/**/*_test.dart"
      - "test/services/**/*_test.dart"
    exclude_patterns:
      - "test/integration/**/*"
      - "test/widget/**/*"
      - "test/a11y/**/*"
    environment_variables:
      TEST_MODE: "true"
      MOCK_SERVICES: "true"
      LOG_LEVEL: "error"

  # Widget Tests
  widget_tests:
    enabled: true
    timeout_minutes: 20
    coverage_threshold: 70
    parallel_jobs: 2
    retry_count: 1
    include_patterns:
      - "test/widget/**/*_test.dart"
      - "test/ui/**/*_test.dart"
    exclude_patterns:
      - "test/integration/**/*"
      - "test/unit/**/*"
    environment_variables:
      TEST_MODE: "true"
      MOCK_SERVICES: "true"
      LOG_LEVEL: "error"

  # Integration Tests
  integration_tests:
    enabled: true
    timeout_minutes: 30
    coverage_threshold: 60
    parallel_jobs: 1
    retry_count: 1
    include_patterns:
      - "integration_test/**/*_test.dart"
      - "test/integration/**/*_test.dart"
    exclude_patterns:
      - "test/unit/**/*"
      - "test/widget/**/*"
    environment_variables:
      TEST_MODE: "true"
      INTEGRATION_TEST: "true"
      LOG_LEVEL: "info"

  # Accessibility Tests
  accessibility_tests:
    enabled: true
    timeout_minutes: 15
    coverage_threshold: 50
    parallel_jobs: 1
    retry_count: 1
    include_patterns:
      - "test/a11y/**/*_test.dart"
      - "test/accessibility/**/*_test.dart"
    exclude_patterns:
      - "test/unit/**/*"
      - "test/widget/**/*"
    environment_variables:
      TEST_MODE: "true"
      ACCESSIBILITY_TEST: "true"
      LOG_LEVEL: "info"

  # Performance Tests
  performance_tests:
    enabled: true
    timeout_minutes: 25
    coverage_threshold: 40
    parallel_jobs: 1
    retry_count: 1
    include_patterns:
      - "integration_test/perf/**/*_test.dart"
      - "test/performance/**/*_test.dart"
    exclude_patterns:
      - "test/unit/**/*"
      - "test/widget/**/*"
    environment_variables:
      TEST_MODE: "true"
      PERFORMANCE_TEST: "true"
      LOG_LEVEL: "info"

  # Security Tests
  security_tests:
    enabled: true
    timeout_minutes: 20
    coverage_threshold: 60
    parallel_jobs: 1
    retry_count: 1
    include_patterns:
      - "test/security/**/*_test.dart"
      - "test/security_rules_test.dart"
    exclude_patterns:
      - "test/unit/**/*"
      - "test/widget/**/*"
    environment_variables:
      TEST_MODE: "true"
      SECURITY_TEST: "true"
      LOG_LEVEL: "info"

# Test Execution Strategy
execution_strategy:
  # Sequential execution for integration and performance tests
  sequential_tests:
    - "integration_tests"
    - "performance_tests"
    - "accessibility_tests"
    - "security_tests"

  # Parallel execution for unit and widget tests
  parallel_tests:
    - "unit_tests"
    - "widget_tests"

# Coverage Configuration
coverage_config:
  # Overall coverage threshold
  overall_threshold: 80
  
  # Per-file coverage thresholds
  file_thresholds:
    lib/models/: 90
    lib/services/: 85
    lib/providers/: 80
    lib/widgets/: 70
    lib/screens/: 75

  # Coverage exclusions
  exclude_patterns:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/test/**"
    - "**/integration_test/**"

# Test Data Configuration
test_data:
  # Mock data files
  mock_files:
    - "test/mocks/mock_data.json"
    - "test/mocks/firebase_mocks.dart"
    - "test/mocks/stripe_mocks.dart"

  # Test fixtures
  fixtures:
    - "test/fixtures/users.json"
    - "test/fixtures/bookings.json"
    - "test/fixtures/payments.json"

# Test Environment Configuration
test_environment:
  # Firebase emulator configuration
  firebase_emulator:
    enabled: true
    auth_port: 9099
    firestore_port: 8080
    functions_port: 5001
    hosting_port: 5000

  # Local development configuration
  local_development:
    debug_mode: true
    log_level: "debug"
    mock_services: true

  # CI/CD configuration
  ci_cd:
    debug_mode: false
    log_level: "error"
    mock_services: true

# Test Reporting Configuration
test_reporting:
  # Coverage report formats
  coverage_formats:
    - "lcov"
    - "html"
    - "json"

  # Test result formats
  result_formats:
    - "junit"
    - "json"
    - "html"

  # Artifact retention
  artifact_retention_days: 30

# Test Performance Optimization
performance_optimization:
  # Parallel test execution
  parallel_execution: true
  max_parallel_jobs: 4

  # Test caching
  enable_test_cache: true
  cache_key: "test-cache-${{ hashFiles('**/pubspec.lock', '**/test/**/*.dart') }}"

  # Test isolation
  isolate_tests: true
  cleanup_after_tests: true

# Test Quality Gates
quality_gates:
  # Minimum test coverage
  minimum_coverage: 80

  # Maximum test duration
  maximum_test_duration_minutes: 30

  # Maximum test failures
  maximum_test_failures: 0

  # Required test types
  required_test_types:
    - "unit_tests"
    - "widget_tests"
    - "integration_tests"

# Test Maintenance
maintenance:
  # Test update schedule
  update_schedule: "weekly"

  # Test review schedule
  review_schedule: "monthly"

  # Test cleanup schedule
  cleanup_schedule: "quarterly"

  # Test documentation update
  documentation_update: "as_needed"

# Test Troubleshooting
troubleshooting:
  # Common test issues
  common_issues:
    - "Test timeout - increase timeout_minutes"
    - "Test flakiness - add retry_count"
    - "Coverage below threshold - add more tests"
    - "Test isolation issues - enable isolate_tests"

  # Debug commands
  debug_commands:
    - "flutter test --verbose"
    - "flutter test --coverage"
    - "flutter test --reporter=expanded"
    - "flutter test --start-paused"

  # Test debugging tips
  debugging_tips:
    - "Use --verbose flag for detailed output"
    - "Check test isolation with --isolate"
    - "Review coverage report for untested code"
    - "Use mock services for external dependencies"