name: Web Deploy

on: workflow_dispatch
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder Web Deploy
        run: echo "Web deploy stub"
