name: Web Deploy

push:
  branches: [ main ]

on:
  pull_request:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Placeholder Web Deploy
        run: echo "Web deploy stub"