name: Web Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "web/**"
      - "marketing/**"
      - "business/**"
      - "admin/**"
      - "enterprise-onboarding-portal/**"
      - ".github/workflows/web-deploy.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "web/**"
      - "marketing/**"
      - "business/**"
      - "admin/**"
      - "enterprise-onboarding-portal/**"
      - ".github/workflows/web-deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: web-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          # Install dependencies for web apps
          for app in web marketing business admin enterprise-onboarding-portal; do
            if [ -f "$app/package.json" ]; then
              echo "Installing dependencies for $app..."
              cd $app
              npm ci
              cd ..
            fi
          done
          
      - name: Build web apps
        run: |
          # Build web apps
          for app in web marketing business admin enterprise-onboarding-portal; do
            if [ -f "$app/package.json" ] && [ -f "$app/package.json" ]; then
              echo "Building $app..."
              cd $app
              if npm run build; then
                echo "✅ $app built successfully"
              else
                echo "⚠️ $app build failed (continuing with others)"
              fi
              cd ..
            fi
          done
          
      - name: Web Deploy Complete
        run: echo "✅ Web deployment preparation complete"